"""Build the static data bundle used by the GitHub Pages case study.

The browser experience deliberately consumes the same committed evaluation
artifacts cited by the README. Keeping this as a build step prevents the site
from drifting away from the model report when results are regenerated.
"""

from __future__ import annotations

import csv
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "docs" / "results"
OUTPUT = ROOT / "assets" / "site-data.js"


def read_csv(name: str) -> list[dict[str, object]]:
    """Read a results CSV and coerce numeric strings for charting."""
    rows: list[dict[str, object]] = []
    with (RESULTS / name).open(newline="", encoding="utf-8") as handle:
        for source_row in csv.DictReader(handle):
            row: dict[str, object] = {}
            for key, value in source_row.items():
                if value is None:
                    row[key] = None
                    continue
                try:
                    row[key] = float(value)
                except ValueError:
                    row[key] = value
            rows.append(row)
    return rows


def main() -> None:
    evaluation = json.loads((RESULTS / "evaluation.json").read_text(encoding="utf-8"))
    test_scores = evaluation["panel_model"]["test_scores"]
    baseline_rmse = next(row["rmse"] for row in test_scores if row["model"] == "lag_12_baseline")
    poisson_rmse = next(row["rmse"] for row in test_scores if row["model"] == "poisson_glm")

    bundle = {
        "generatedFrom": "docs/results",
        "snapshotDate": "2026-09-16",
        "stats": {
            "vehicles": evaluation["data"]["wa_unique_vehicles"],
            "transactions": evaluation["data"]["electric_transactions_total"],
            "counties": evaluation["data"]["counties"],
            "observedRangeShare": evaluation["data"]["observed_range_share"],
            "poissonImprovementPct": round((baseline_rmse - poisson_rmse) / baseline_rmse * 100, 1),
            "mlBetterCounties": evaluation["county_error_summary"]["ml_better_counties"],
        },
        "modelScores": test_scores,
        "validationScores": evaluation["panel_model"]["validation_scores"],
        "stateScores": evaluation["state_backtest"]["holdout_scores"],
        "countyErrors": read_csv("county_error_analysis.csv"),
        "predictionIntervals": read_csv("prediction_intervals.csv"),
        "rangeSensitivity": read_csv("range_threshold_sensitivity.csv"),
        "temporalRobustness": read_csv("temporal_robustness.csv"),
        "ablation": read_csv("ablation_results.csv"),
        "intervalCoverage": read_csv("interval_coverage.csv"),
    }

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    json_payload = json.dumps(bundle, separators=(",", ":"), ensure_ascii=False)
    OUTPUT.write_text(
        "/* Generated by scripts/build_site_data.py. Do not edit manually. */\n"
        f"window.CHARGEFORWARD_DATA={json_payload};\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUTPUT.relative_to(ROOT)} ({OUTPUT.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
